=== hmrc/lisa-api/public/api/conf/1.0/schemas/BonusPaymentRequest.post.schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties":
	{
		"lisaTransactionID" : {"$ref": "#/definitions/IDType"},
		"lisaInvestorAccountID" : {"$ref": "#/definitions/IDType"},
		"lisaManagerReferenceNumber" : {"$ref": "#/definitions/LISAManagerReferenceNumberType"},
        "lifeEventID" : {"$ref": "#/definitions/IDType"},
		"claimPeriodStartDate" : {"$ref": "#/definitions/ISO8601-Date"},
	    "claimPeriodEndDate" : {"$ref": "#/definitions/ISO8601-Date"},
        "claimReason" : {"$ref": "#/definitions/claimReasonType"},

		"htbTransfer" :
		{
			"type" : "object",
			"properties":
			{
				"SubscriptionAmountInClaimPeriod" :{"type" : "number"},
			    "totalAmountToDate" :{"type" : "number"}
			}
		},

		"subscriptions" :
		{
			"type" : "object",
			"properties":
			{
			  "newSubscriptionsInClaimPeriod" :{"type" : "number"},
			  "newSubscriptionsTaxYearToDate" :{"type" : "number"},
			  "totalSubscriptionsInClaimPeriod" :{"type" : "number"},
			  "totalSubscriptionsTaxYearToDate" :{"type" : "number"}
			},
		  "required":
		  [
			"newSubscriptionsTaxYearToDate",
			"totalSubscriptionsInClaimPeriod",
			"totalSubscriptionsTaxYearToDate"
		  ]
		},
      "bonuses" :
      {
        "type": "object",
        "properties" :
        {
          "bonusDueInClaimPeriod" :{"type" : "number"},
          "bonusDueYearToDate" :{"type" : "number"},
          "bonusPaidInTaxYearToDate" :{"type" : "number"}
        },
        "required":
        [
          "bonusDueInClaimPeriod" ,
          "bonusDueYearToDate"
        ]

      }

	},
	"required": [
		"lisaInvestorAccountID",
		"lisaManagerReferenceNumber",
		"claimPeriodStartDate",
		"claimPeriodEndDate",
        "claimReason",
		"subscriptions",
        "bonuses"
    ],
	"additionalProperties": false,
	"definitions":
	{
      "ISO8601-Date": {
        "type": "string",
        "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
      },
		"IDType": {
			"type": "string",
			"pattern": "^\\d{10}$"
		},
		"LISAManagerReferenceNumberType" : {
			"type" : "string",
			"pattern": "^Z\\d{6}$"
		},
      "claimReasonType" : {
        "type" : "string",
        "enum": ["Life Event", "Regular Bonus"]
      }

	}
}

=== hmrc/lisa-api/public/api/conf/1.0/examples/BonusPaymentRequest.post.json
{
  "lisaInvestorAccountID" : "1234567890",
  "lisaManagerReferenceNumber" : "Z543210",
  "lifeEventID" : "1234567891",
  "claimPeriodStartDate" : "2016-12-22",
  "claimPeriodEndDate" : "2016-12-22",
  "claimReason" : "Life Event",
  "htbTransfer" : {
    "SubscriptionAmountInClaimPeriod" : 0,
    "totalAmountToDate" : 0
  },
  "subscriptions"   :
  {
    "newSubscriptionsInClaimPeriod" : 4000,
    "newSubscriptionsTaxYearToDate" : 4000,
    "totalSubscriptionsInClaimPeriod" : 4000,
    "totalSubscriptionsTaxYearToDate" : 4000
  },
  "bonuses"   :
  {
    "bonusDueInClaimPeriod" : 1000,
    "bonusDueYearToDate" : 1000
  }
}
