=== hmrc/lisa-api/public/api/conf/1.0/schemas/LISAAccount.put.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
	"investorID": {
	  "$ref": "#/definitions/IDType"
	},
	"lisaInvestorAccountID": {
	  "type": "string"
	},
	"lisaManagerReferenceNumber": {
	  "$ref": "#/definitions/LISAManagerReferenceNumberType"
	},
	"PrevLisaInvestorAccountID": {
	  "type": "string"
	},
	"PrevLisaManagerReferenceNumber": {
	  "$ref": "#/definitions/LISAManagerReferenceNumberType"
	},
	"transferOutDate": {
	  "$ref": "#/definitions/ISO8601-Date"
	},
	"transferInDate": {
	  "$ref": "#/definitions/ISO8601-Date"
	},
	"accountCreationReason": {
	  "type": "string",
	  "enum": [
		"New Account",
		"Transferred Account"
	  ]
	},
	"accountClosureReason": {
	  "type": "string",
	  "enum": [
		"Transferred-out",
		"All funds withdrawn",
		"Voided"
	  ]
	},
	"closureDate": {
	  "$ref": "#/definitions/ISO8601-Date"
	},
	"firstSubscriptionDate": {
	  "$ref": "#/definitions/ISO8601-Date"
	},
	"investorNINO": {
	  "$ref": "#/definitions/NINOType"
	}
  },
	"required": [
	  "investorID",
	  "lisaManagerReferenceNumber",
	  "PrevLisaInvestorAccountID",
	  "PrevLisaManagerReferenceNumber",
	  "transferInDate",
	  "accountCreationReason",
	  "firstSubscriptionDate",
	  "investorNINO"
	],
	"additionalProperties": false,
	"definitions": {
	  "ISO8601-Date": {
		"type": "string",
		"pattern": "^\\d{4}-\\d{2}-\\d{2}$"
	  },
	  "ISO8601-Timestamp": {
		"type": "string",
		"pattern": "\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}(:\\d{2})?(([+-]\\d{2}(:\\d{2})?)|Z)"
	  },
	  "IDType": {
		"type": "string",
		"pattern": "^\\d{10}$"
	  },
	  "LISAManagerReferenceNumberType": {
		"type": "string",
		"pattern": "^Z\\d{6}$"
	  },
	  "NINOType": {
		"type": "string",
		"pattern": "^[A-Z]{2}\\d{6}[A-D]$"
	  }
	}

}

=== hmrc/lisa-api/public/api/conf/1.0/examples/LISAAccount.put.json
{
  "investorID" : "8765432100",
  "lisaManagerReferenceNumber" : "Z543210",
  "PrevLisaInvestorAccountID": "Z543210",
  "PrevLisaManagerReferenceNumber" : "Z543333",
  "transferInDate" : "2015-12-13",

  "accountCreationReason" : "Transferred Account",

  "firstSubscriptionDate" : "2011-02-02",
  "investorNINO":"AB123456D"
}
