=== hmrc/lisa-api/resources/public/api/conf/2.0/schemas/LifeEvent.get.array.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "minItems": 1,
  "maxItems": 4,
  "uniqueItems": true,
  "items": {
    "type": "object",
    "properties": {
      "lifeEventId": {
        "$ref": "#/definitions/IDType",
        "description": "The ID for the life event."
      },
      "eventType" : {
        "$ref": "#/definitions/eventType",
        "description": "The type of life event."
      },
      "eventDate" : {
        "$ref": "#/definitions/ISO8601-Date",
        "description": "This is the date the life event was reported."
      },
      "withdrawalAmount": {
        "type": "number",
        "description": "This is the amount that the investor has withdrawn from the LISA account."
      },
      "conveyancerReference": {
        "description": "This is the reference for the conveyancer involved with the property purchase.",
        "type": "string",
        "pattern": "^[a-zA-Z0-9 :/-]{1,20}$",
        "example": "CR12345-6789"
      },
      "propertyDetails": {
        "type": "object",
        "description": "The details of the property that you requested funds to buy.",
        "properties": {
          "nameOrNumber": {
            "description": "The name or number of the property that you requested funds to buy.",
            "type": "string",
            "pattern": "^[A-Za-z0-9 :/-]{1,35}$",
            "example": "Flat A"
          },
          "postalCode": {
            "description": "The postcode of the property that you requested funds to buy.",
            "type": "string",
            "pattern": "^[A-Za-z0-9 ]{1,8}$",
            "example": "AA1 1AA"
          }
        },
        "required": [
          "nameOrNumber",
          "postalCode"
        ],
        "additionalProperties": false
      },
      "fundReleaseId": {
        "$ref": "#/definitions/IDType",
        "description": "The ID of the fund release for an extension or purchase outcome."
      },
      "propertyPurchaseValue": {
        "type": "number",
        "description": "The value of the property that the investor purchased. Only included if the purchase was completed."
      },
      "propertyPurchaseResult": {
        "description": "Whether a property purchase was completed or failed.",
        "type": "string",
        "enum": ["Purchase failed", "Purchase completed"]
      },
      "lisaManagerName": {
        "type": "string",
        "description": "The name of the LISA provider.",
        "maxLength": 50,
        "pattern": "^[a-zA-Z0-9 '/,&().-]{1,50}$",
        "example": "Company Name"
      },
      "taxYear": {
        "type": "integer",
        "description": "The tax year for the return of information. This will be the year that the tax year ends in. For example, for the 2017 to 2018 tax year it will be 2018.",
        "min": 2017,
        "pattern": "^[0-9]{4}$",
        "example": "2018"
      },
      "marketValueCash": {
        "$ref": "#/definitions/MarketValue",
        "description": "The total value that was reported for the cash LISA account."
      },
      "marketValueStocksAndShares": {
        "$ref": "#/definitions/MarketValue",
        "description": "The total value that was reported for the stocks and shares LISA account."
      },
      "annualSubsCash": {
        "$ref": "#/definitions/AnnualSubs",
        "description": "The total value that was reported for investor subscriptions into their cash LISA account during the tax year."
      },
      "annualSubsStocksAndShares": {
        "$ref": "#/definitions/AnnualSubs",
        "description": "The total value that was reported for investor subscriptions into their stocks and shares LISA account during the tax year."
      },
      "supersede": {
        "type": "object",
        "description": "Shows that a life event was corrected.",
        "properties": {
          "originalLifeEventId": {
            "description": "The ID of the life event that was corrected.",
            "$ref": "#/definitions/IDType"
          },
          "originalFundReleaseId": {
            "description": "The ID of the fund release that was corrected.",
            "$ref": "#/definitions/IDType"
          },
          "originalExtensionId": {
            "description": "The ID of the purchase extension that was corrected.",
            "$ref": "#/definitions/IDType"
          },
          "originalPurchaseOutcomeId": {
            "description": "The ID of the purchase outcome that was corrected.",
            "$ref": "#/definitions/IDType"
          },
          "originalEventDate": {
            "description": "The eventDate of the life event that was corrected.",
            "$ref": "#/definitions/ISO8601-Date",
            "example": "2017-05-11"
          }
        },
        "required": [
          "originalEventDate"
        ],
        "additionalProperties": false
      },
      "supersededBy": {
        "$ref": "#/definitions/IDType",
        "description": "The ID of the life event that supersedes the current one."
      }
    },
    "additionalProperties": false,
    "required": [
      "lifeEventId",
      "eventType",
      "eventDate"
    ]
  },
  "definitions":
  {
    "IDType": {
      "type": "string",
      "pattern": "^\\d{10}$",
      "example": "0987654321"
    },
    "ISO8601-Date" : {
      "id": "full-date",
      "type": "string",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}$",
      "example": "2017-05-20"
    },
    "eventType" : {
      "type" : "string",
      "enum": ["LISA Investor Terminal Ill Health", "LISA Investor Death", "Funds release", "Extension one", "Extension two", "Purchase outcome"]
    },
    "AnnualSubs": {
      "type": "integer",
      "minimum": 0,
      "maximum": 9999,
      "pattern": "^[0-9]{1,4}$",
      "example": "100"
    },
    "MarketValue": {
      "type": "integer",
      "minimum": 0,
      "maximum": 999999,
      "pattern": "^[0-9]{1,6}$",
      "example": "1000"
    }
  }
}

=== hmrc/lisa-api/resources/public/api/conf/2.0/examples/LifeEvent.get.property-purchase.array.json
[
  {
    "lifeEventId": "3456789001",
    "eventType": "Funds release",
    "eventDate": "2017-05-05",
    "withdrawalAmount": 5000.00,
    "supersede": {
      "originalLifeEventId": "3456789000",
      "originalEventDate": "2017-05-10"
    }
  },
  {
    "lifeEventId": "6789000002",
    "eventDate": "2017-05-11",
    "eventType": "Extension one",
    "supersede": {
      "originalEventDate": "2017-05-10",
      "originalLifeEventId": "6789000001"
    }
  },
  {
    "lifeEventId": "6789000004",
    "eventDate": "2017-08-11",
    "eventType": "Extension two",
    "supersede": {
      "originalEventDate": "2017-08-10",
      "originalLifeEventId": "6789000003"
    }
  },
  {
    "lifeEventId": "5678900002",
    "fundReleaseId": "3456789001",
    "eventDate": "2017-06-10",
    "eventType": "Purchase outcome",
    "propertyPurchaseResult": "Purchase completed",
    "propertyPurchaseValue": 250000,
    "supersede": {
      "originalLifeEventId": "5678900001",
      "originalEventDate": "2017-05-05"
    }
  }
]
