=== hmrc/lisa-api/resources/public/api/conf/1.0/schemas/BonusPaymentRequest.get.schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties":
	{
        "lifeEventId" : {
          "description": "The reference number you get when you report a life event.",
          "$ref": "#/definitions/IDType"},
		"periodStartDate" : {
          "description": "The first date in the claim period. The periodStartDate must be the 6th day of the month. You can’t enter a date in the future for periodStartDate.",
          "$ref": "#/definitions/ISO8601-Date"},
	    "periodEndDate" : {
          "description": "The end date of the claim period. The periodEndDate must be the 5th day of the month. It has to be the month after the periodStartDate.",
          "$ref": "#/definitions/ISO8601-Date1"},

		"htbTransfer" :
		{
          "description": "Details about Help-To-Buy funds.",
			"type" : "object",
			"properties":
			{
				"htbTransferInForPeriod" :{
                  "description": "The total amount of Help to Buy funds in the account during the claim period. You can include an amount up to 2 decimal places. You must enter a number greater than 0 in either newSubsForPeriod or htbTransferInForPeriod. Both fields can’t be 0. If there is a number in htbTransferInForPeriod, then the number in htbTransferTotalYTD must be greater than 0.",
                  "type" : "number"},
			    "htbTransferTotalYTD" :{
                  "description": "The total amount of Help to Buy funds in the account in the tax year to date. You can include an amount up to 2 decimal places. If there is a number in htbTransferInForPeriod, then the number in htbTransferTotalYTD must be greater than 0.",
                  "type" : "number"}
			},
          "required":
          [
            "htbTransferInForPeriod",
            "htbTransferTotalYTD"
          ]
		},

		"inboundPayments" :
		{
          "description": "Details about qualifying deposits and account balance.",
			"type" : "object",
			"properties":
			{
			  "newSubsForPeriod" :{"description": "The total value of new qualifying deposits paid into to the account during the claim period. You can include an amount up to 2 decimal places. You must enter a number greater than 0 in either newSubsForPeriod or htbTransferInForPeriod. Both fields can’t be 0. If there is a number in newSubsForPeriod, then the number in newSubsYTD must be greater than 0.", "type" : "number"},
			  "newSubsYTD" :{"description": "The total value of new qualifying deposits paid into the account during the tax year to date. You can include an amount up to 2 decimal places. If there is a number in newSubsForPeriod, then the number in newSubsYTD must be greater than 0.", "type" : "number"},
			  "totalSubsForPeriod" :{"description": "The total amount in the account during the claim period that qualifies for a bonus payment. You can include an amount up to 2 decimal places. The totalSubsForPeriod must always be greater than 0.", "type" : "number"},
			  "totalSubsYTD" :{"description": "The total amount in the account during the tax year to date that qualifies for a bonus payment. You can include an amount up to 2 decimal places. The totalSubsYTD must be the same as or more than totalSubsForPeriod.", "type" : "number"}
			},
		  "required":
		  [
			"newSubsYTD",
			"totalSubsForPeriod",
			"totalSubsYTD"
		  ]
		},
      "bonuses" :
      {
        "description": "Bonus payment details.",
        "type": "object",
        "properties" :
        {
          "bonusDueForPeriod" :{"description": "The total bonus payment amount due for the claim period. You can include an amount up to 2 decimal places. The bonusDueForPeriod must always be greater than 0.", "type" : "number"},
          "totalBonusDueYTD" :{"description": "The total bonus payment amount due for the tax year to date. You can include an amount up to 2 decimal places. The totalBonusDueYTD must always be greater than 0.", "type" : "number"},
          "bonusPaidYTD" :{"description": "The total bonus payment that has already been claimed and paid in the tax year to date. You can include an amount up to 2 decimal places.", "type" : "number"},
          "claimReason" : {"description": "The reason the bonus payment was claimed.", "$ref": "#/definitions/claimReasonType"}
        },
        "required":
        [
          "bonusDueForPeriod" ,
          "totalBonusDueYTD",
          "claimReason"
        ]

      }

	},
	"required": [
		"periodStartDate",
		"periodEndDate",
		"inboundPayments",
        "bonuses"
    ],
	"additionalProperties": false,
	"definitions":
	{
      "ISO8601-Date": {
        "id": "full-date",
        "type": "string",
        "pattern": "^\\d{4}-\\d{2}-\\d{2}$",
        "example": "2017-05-06"
      },
      "ISO8601-Date1": {
        "id": "full-date",
        "type": "string",
        "pattern": "^\\d{4}-\\d{2}-\\d{2}$",
        "example": "2017-05-05"
      },
		"IDType": {
			"type": "string",
			"pattern": "^\\d{10}$",
          "example": "0987654321"
		},
      "claimReasonType" : {
        "type" : "string",
        "enum": ["Life Event", "Regular Bonus"]
      },
      "chargeReasonType" : {
        "type" : "string",
        "enum": ["Unauthorised withdrawal", "Others TBD"]
      }
	}
}

=== hmrc/lisa-api/resources/public/api/conf/1.0/examples/BonusPaymentRequest.post.2.json
{
  "periodStartDate": "2017-04-06",
  "periodEndDate": "2017-05-05",
  "inboundPayments": {
    "newSubsForPeriod": 4000.00,
    "newSubsYTD": 4000.00,
    "totalSubsForPeriod": 4000.00,
    "totalSubsYTD": 4000.00
  },
  "bonuses": {
    "bonusPaidYTD": 0.0,
    "bonusDueForPeriod": 1000.00,
    "totalBonusDueYTD": 1000.00,
    "claimReason": "Regular Bonus"
  }
}

=== hmrc/lisa-api/resources/public/api/conf/1.0/examples/LISATransaction.get.response.1.json
{
  "periodStartDate": "2017-04-06",
  "periodEndDate": "2017-05-05",
  "inboundPayments": {
    "newSubsForPeriod": 4000,
    "newSubsYTD": 4000,
    "totalSubsForPeriod": 40000,
    "totalSubsYTD": 40000
  },
  "bonuses": {
    "bonusPaidYTD": 0,
    "bonusDueForPeriod": 10000,
    "totalBonusDueYTD": 10000,
    "claimReason": "Regular Bonus"
  }
}

=== hmrc/lisa-api/resources/public/api/conf/1.0/examples/LISATransaction.get.response.json
{
  "lifeEventId": "1234567890",
  "periodStartDate": "2017-04-06",
  "periodEndDate": "2017-05-05",
  "htbTransfer": {
    "htbTransferInForPeriod": 0,
    "htbTransferTotalYTD": 0
  },
  "inboundPayments": {
    "newSubsForPeriod": 4000,
    "newSubsYTD": 4000,
    "totalSubsForPeriod": 4000,
    "totalSubsYTD": 4000
  },
  "bonuses": {
    "bonusDueForPeriod": 1000,
    "totalBonusDueYTD": 1000,
    "claimReason": "Life Event"
  }
}
