=== hmrc/lisa-api/resources/public/api/conf/1.0/schemas/LISAAccount.get.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "investorId": {
      "description": "The investor’s ID reference number.",
      "$ref": "#/definitions/IDType",
      "example": "9876543210"
    },
    "accountId": {
      "description": "The provider’s own unique reference number for the investor’s LISA account.",
      "$ref": "#/definitions/accountIdType",
      "example": "AB76543210"
    },
    "creationReason": {
      "description": "The reason the account was created.",
      "type": "string",
      "enum": [
        "New",
        "Transferred"
      ]
    },
    "firstSubscriptionDate": {
      "description":"The date of the first deposit into the account. If this is a transfer, use the date of deposit into the account managed by the previous provider. This cannot be in the future.",
      "$ref": "#/definitions/ISO8601-Date"
    },
    "accountStatus": {
      "description": "The status of the account.",
      "type": "string",
      "enum": [
        "OPEN",
        "VOID",
        "CLOSED"
      ]
    },
    "subscriptionStatus": {
      "description": "The subscription status for the current tax year.",
      "type": "string",
      "enum": [
        "AVAILABLE",
        "ACTIVE",
        "LOCKED",
        "CANCELLED",
        "VOID"
      ]
    },
    "accountClosureReason": {
      "description": "The reason the account was closed.",
      "type": "string"
    },
    "closureDate": {
      "description": "The date the account was closed. This cannot be in the future.",
      "$ref": "#/definitions/ISO8601-Date"
    },

    "transferAccount": {
      "type": "object",
      "description" : "If the creationReason is ‘Transferred’, then this is required.",
      "properties": {
        "transferredFromAccountId": {
          "description" : "The previous provider's own unique reference number for the investor’s LISA account.",
          "$ref": "#/definitions/accountIdType",
          "example": "987654320"
        },
        "transferredFromLMRN": {
          "description" : "The reference given to the LISA provider when they applied for approval from HMRC.",
          "$ref": "#/definitions/LISAManagerReferenceNumberType",
          "example": "Z4567"
        },
        "transferInDate": {
          "description": "The date the account transferred from the previous provider to the new one. This cannot be in the future.",
          "$ref": "#/definitions/ISO8601-Date"
        }
      },
      "required": [
        "transferredFromAccountId",
        "transferredFromLMRN",
        "transferInDate"
      ]
    }
  }
,

  "required": [
    "investorId",
    "accountId",
    "creationReason",
    "firstSubscriptionDate",
    "accountStatus"
  ],
  "additionalProperties": false,
  "definitions": {
    "ISO8601-Date": {
      "id": "full-date",
      "type": "string",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}$",
      "example": "2017-04-20"
    },
    "IDType": {
      "type": "string",
      "pattern": "^\\d{10}$",
      "example": "1234567890"
    },
    "LISAManagerReferenceNumberType": {
      "type": "string",
      "pattern": "^Z([0-9]{4}|[0-9]{6})$",
      "example": "Z1234"
    }
  ,
    "accountIdType": {
      "type": "string",
      "example": "AB9876543210",
      "pattern": "^[a-zA-Z0-9 :/-]{1,20}$"
    }
  }


}

=== hmrc/lisa-api/resources/public/api/conf/2.0/examples/LISAAccount.get1.json
{
  "investorId": "9876543210",
  "creationReason": "Transferred",
  "accountId": "1234567891",
  "firstSubscriptionDate": "2017-04-06",
  "accountStatus": "OPEN",
  "subscriptionStatus": "AVAILABLE",
  "transferAccount": {
    "transferredFromAccountId": "8765432100",
    "transferredFromLMRN": "Z654321",
    "transferInDate": "2017-04-06"
  }
}

=== hmrc/lisa-api/resources/public/api/conf/1.0/examples/LISAAccount.get.json
{
  "accountId": "0000000200",
  "investorId": "9876543210",
  "creationReason": "Transferred",
  "firstSubscriptionDate": "2017-04-06",
  "accountStatus": "OPEN",
  "subscriptionStatus": "ACTIVE",
  "transferAccount": {
    "transferredFromAccountId": "8765432102",
    "transferredFromLMRN": "Z543333",
    "transferInDate": "2017-04-06"
  }
}
